// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	model "ai-job-assistant/backend/internal/domain/model"
	context "context"

	mock "github.com/stretchr/testify/mock"

	port "ai-job-assistant/backend/internal/domain/port"

	uuid "github.com/google/uuid"
)

// MockVacancyRepository is an autogenerated mock type for the VacancyRepository type
type MockVacancyRepository struct {
	mock.Mock
}

type MockVacancyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVacancyRepository) EXPECT() *MockVacancyRepository_Expecter {
	return &MockVacancyRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, vacancy
func (_m *MockVacancyRepository) Create(ctx context.Context, vacancy *model.Vacancy) error {
	ret := _m.Called(ctx, vacancy)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Vacancy) error); ok {
		r0 = rf(ctx, vacancy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVacancyRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockVacancyRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - vacancy *model.Vacancy
func (_e *MockVacancyRepository_Expecter) Create(ctx interface{}, vacancy interface{}) *MockVacancyRepository_Create_Call {
	return &MockVacancyRepository_Create_Call{Call: _e.mock.On("Create", ctx, vacancy)}
}

func (_c *MockVacancyRepository_Create_Call) Run(run func(ctx context.Context, vacancy *model.Vacancy)) *MockVacancyRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Vacancy))
	})
	return _c
}

func (_c *MockVacancyRepository_Create_Call) Return(_a0 error) *MockVacancyRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVacancyRepository_Create_Call) RunAndReturn(run func(context.Context, *model.Vacancy) error) *MockVacancyRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateMany provides a mock function with given fields: ctx, vacancies
func (_m *MockVacancyRepository) CreateMany(ctx context.Context, vacancies []*model.Vacancy) (port.CreateManyResult, error) {
	ret := _m.Called(ctx, vacancies)

	if len(ret) == 0 {
		panic("no return value specified for CreateMany")
	}

	var r0 port.CreateManyResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []*model.Vacancy) (port.CreateManyResult, error)); ok {
		return rf(ctx, vacancies)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []*model.Vacancy) port.CreateManyResult); ok {
		r0 = rf(ctx, vacancies)
	} else {
		r0 = ret.Get(0).(port.CreateManyResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []*model.Vacancy) error); ok {
		r1 = rf(ctx, vacancies)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVacancyRepository_CreateMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMany'
type MockVacancyRepository_CreateMany_Call struct {
	*mock.Call
}

// CreateMany is a helper method to define mock.On call
//   - ctx context.Context
//   - vacancies []*model.Vacancy
func (_e *MockVacancyRepository_Expecter) CreateMany(ctx interface{}, vacancies interface{}) *MockVacancyRepository_CreateMany_Call {
	return &MockVacancyRepository_CreateMany_Call{Call: _e.mock.On("CreateMany", ctx, vacancies)}
}

func (_c *MockVacancyRepository_CreateMany_Call) Run(run func(ctx context.Context, vacancies []*model.Vacancy)) *MockVacancyRepository_CreateMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*model.Vacancy))
	})
	return _c
}

func (_c *MockVacancyRepository_CreateMany_Call) Return(_a0 port.CreateManyResult, _a1 error) *MockVacancyRepository_CreateMany_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVacancyRepository_CreateMany_Call) RunAndReturn(run func(context.Context, []*model.Vacancy) (port.CreateManyResult, error)) *MockVacancyRepository_CreateMany_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockVacancyRepository) Get(ctx context.Context, id uuid.UUID) (*model.Vacancy, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Vacancy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Vacancy, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Vacancy); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Vacancy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVacancyRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockVacancyRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockVacancyRepository_Expecter) Get(ctx interface{}, id interface{}) *MockVacancyRepository_Get_Call {
	return &MockVacancyRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockVacancyRepository_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockVacancyRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockVacancyRepository_Get_Call) Return(_a0 *model.Vacancy, _a1 error) *MockVacancyRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVacancyRepository_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Vacancy, error)) *MockVacancyRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, query
func (_m *MockVacancyRepository) List(ctx context.Context, query port.ListVacanciesQuery) ([]*model.Vacancy, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*model.Vacancy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, port.ListVacanciesQuery) ([]*model.Vacancy, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, port.ListVacanciesQuery) []*model.Vacancy); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Vacancy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, port.ListVacanciesQuery) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVacancyRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockVacancyRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - query port.ListVacanciesQuery
func (_e *MockVacancyRepository_Expecter) List(ctx interface{}, query interface{}) *MockVacancyRepository_List_Call {
	return &MockVacancyRepository_List_Call{Call: _e.mock.On("List", ctx, query)}
}

func (_c *MockVacancyRepository_List_Call) Run(run func(ctx context.Context, query port.ListVacanciesQuery)) *MockVacancyRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(port.ListVacanciesQuery))
	})
	return _c
}

func (_c *MockVacancyRepository_List_Call) Return(_a0 []*model.Vacancy, _a1 error) *MockVacancyRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockVacancyRepository_List_Call) RunAndReturn(run func(context.Context, port.ListVacanciesQuery) ([]*model.Vacancy, error)) *MockVacancyRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVacancyRepository creates a new instance of MockVacancyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVacancyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVacancyRepository {
	mock := &MockVacancyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
